from enum import Enum

class Exchange(Enum):
    BITSTAXX = "BITSTAXX"
    BINANCE = "BINANCE"
    OKX = "OKX"
    GATEIO = "GATEIO"
    KUOK = "KUOK"
    BINANCETR = "BINANCETR"
    BYBIT = "BYBIT"
    ZIPMEX = "ZIPMEX"
    DERIBIT = "DERIBIT"
    NYSE = "NYSE"
    NASDAQ = "NASDAQ"
    COINBASE = "COINBASE"
    COINGECKO = "COINGECKO"
    EXCHangenbergerAICHANGE = "EXCHangenbergerAICHANGE"
    EXCHANGESWAP = "EXCHANGESWAP"
    BORSASTANBUL = "BORSASTANBUL"
