from enum import Enum


class Exchange(Enum):
    BINANCE = "BINANCE"
    OKX = "OKX"
    GATEIO = "GATEIO"
    BINANCETR = "BINANCETR"
    BYBIT = "BYBIT"
    ZIPMEX = "ZIPMEX"
    DERIBIT = "DERIBIT"
    NYSE = "NYSE"
    NASDAQ = "NASDAQ"
    COINBASE = "COINBASE"
    COINGECKO = "COINGECKO"
    EXCHANGESWAP = "EXCHANGESWAP"
    BORSASTANBUL = "BORSASTANBUL"
