from enum import Enum


class TransformTypes(Enum):
    BINANCEHD_TO_OHLCV = "BINANCEHD_TO_OHLCV"
    COINGECKOHD_TO_OHLCV = "COINGECKOHD_TO_OHLCV"
    COINGECKOCOINDATA_TO_NVT = "COINGECKOCOINDATA_TO_NVT"
    OHLCV_TO_TA = "OHLCV_TO_TA"
    TA_TO_JSON = "TA_TO_JSON"
    TA_TO_DATAFRAME = "TA_TO_DATAFRAME"
    DATA_TO_PICKLE = "DATA_TO_PICKLE"
